---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:    
      nodeName: node0
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m 
              memory: 256Mi
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: "ZIGBEE2MQTT_DATA"
              value: "/data"
            - name: ZIGBEE2MQTT_CONFIG_BASE_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: ZIGBEE2MQTT_BASE_TOPIC
                  name: mqtt-data
                  optional: false
            - name: ZIGBEE2MQTT_CONFIG_MQTT_SERVER
              valueFrom:
                configMapKeyRef:
                  key: MQTT_BROKER_ZIGBEE
                  name: mqtt-data
                  optional: false
            - name: ZIGBEE2MQTT_CONFIG_SERIAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: ZIGBEE_ADDRESS
                  name: mqtt-data
                  optional: false
            - name: ZIGBEE2MQTT_CONFIG_MQTT_USER
              valueFrom:
                secretKeyRef:
                  key: MQTT_USER
                  name: mqtt-creds
                  optional: false
            - name: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MQTT_SECRET
                  name: mqtt-creds
                  optional: false
          securityContext:
            privileged: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: zigbee2mqtt-data
            - mountPath: /app/configuration.yaml
              name: zigbee2mqtt-config
              subPath: configuration.yaml
            - mountPath: /run/udev
              name: zigbee2mqtt-udev
            - mountPath: /dev/zigbee
              name: ttyusb
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
      - name: zigbee2mqtt-data
        persistentVolumeClaim:
          claimName: zigbee2mqtt-data
      - hostPath:
          path: /run/udev
          type: ''
        name: zigbee2mqtt-udev
      - hostPath:
          path: /dev/zigbee
          type: ''
        name: ttyusb
      - configMap:
          defaultMode: 420
          name: zigbee2mqtt-config
        name: zigbee2mqtt-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt-data
  namespace: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  ports:
    - name: zigbee2mqtt
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: zigbee2mqtt
  type:
    ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: zigbee.local.example.com
      http:
        paths:
          - backend:
              service:
                name: zigbee2mqtt
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific